vich_uploader:
    db_driver: orm

    mappings:
        organisation_images:
            uri_prefix:         '%app.path.organisation_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.organisation_images%'
