#index:
#    path: /
#    controller: App\Controller\DefaultController::index
easy_admin_bundle:
  resource: 'App\Controller\AdminController'
  prefix: /admin
  type: annotation

page_controller:
  resource: ../src/Controller/PageController.php
  type: annotation